## This script is generated by ChatGPT given the Amazon Statefunction Language (ASL) taken from the following youtube tutorial.

## https://www.youtube.com/watch?v=DFSko_sLyMM&list=PL9nWRykSBSFgQrO66TmO1vHFP6yuPF5G-&index=12

import boto3
import json, os

from dotenv import load_dotenv

load_dotenv("../env")
AWS_ALL_IN_ONE_SG = os.environ["AWS_ALL_IN_ONE_SG"]
ACCOUNT_ID = os.environ["AWS_ACCOUNT_ID_ROOT"]
REGION = os.environ["AWS_DEFAULT_REGION"]

# Initialize boto3 clients for Step Functions and DynamoDB
sfn_client = boto3.client('stepfunctions', region_name=REGION)
dynamodb_client = boto3.client('dynamodb', region_name=REGION)

# Create the DynamoDB table
table_name = 'CustomerOrdersTable'
try:
    dynamodb_client.create_table(
        TableName=table_name,
        KeySchema=[
            {
                'AttributeName': 'customerId',
                'KeyType': 'HASH'
            },
            {
                'AttributeName': 'orderId',
                'KeyType': 'RANGE'
            }
        ],
        AttributeDefinitions=[
            {
                'AttributeName': 'customerId',
                'AttributeType': 'S'
            },
            {
                'AttributeName': 'orderId',
                'AttributeType': 'S'
            }
        ],
        ProvisionedThroughput={
            'ReadCapacityUnits': 5,
            'WriteCapacityUnits': 5
        }
    )
    print(f"Creating DynamoDB table {table_name}...")
except dynamodb_client.exceptions.ResourceInUseException:
    print(f"DynamoDB table {table_name} already exists.")

state_machine_definition = {
    # Optional comment describing the purpose of the state machine
    "Comment": "A description of my state machine",
    # The name of the state to start execution with
    "StartAt": "Add Order Entry",
    # All states in the state machine are defined under the "States" key
    "States": {
        # First state: Add Order Entry
        "Add Order Entry": {
            "Type": "Pass",  # A Pass state simply passes its input to output without any work
            "Result": "Order Entry Added",  # This is the hardcoded result/output
            "Next": "Choice",  # Next state to transition to
        },
        # A dummy choice state (Note: it's a Pass state here, not a real Choice type)
        "Choice": {
            "Type": "Pass",  # Again, just passing data through
            "Result": "Choice State",  # Hardcoded result to simulate a decision point
            "Next": "Call Credit Card Service To Charge Customer",  # Moves to Lambda task
        },
        # Lambda Task to charge the customer
        "Call Credit Card Service To Charge Customer": {
            "Type": "Task",  # A Task state performs actual work by invoking a resource
            "Resource": "arn:aws:states:::lambda:invoke",  # Managed integration with AWS Lambda
            # Parameters to send to the Lambda function
            "Parameters": {
                "Payload.$": "$",  # Sends the entire state input as the payload
                "FunctionName": "arn:aws:lambda:us-east-1:755314965794:function:Test:$LATEST",  # Lambda function to invoke
            },
            # Retry policy configuration
            "Retry": [
                {
                    "ErrorEquals": [  # Types of errors to retry on
                        "Lambda.ServiceException",
                        "Lambda.AWSLambdaException",
                        "Lambda.SdkClientException",
                    ],
                    "IntervalSeconds": 2,  # Wait 2 seconds before retrying
                    "MaxAttempts": 6,  # Retry up to 6 times
                    # Exponential backoff: A multiplier that increases the delay time exponentially for each retry
                    "BackoffRate": 2,  # Delay_n = IntervalSeconds × (BackoffRate)^(n-1)
                }
            ],
            "Next": "Success",  # If successful, go to the Success state
            # Catch any errors if the Lambda fails
            "Catch": [
                {
                    "ErrorEquals": [
                        "States.ALL"  # Catch all errors
                    ],
                    "Next": "Fallback - Delete failed order",  # Go to a cleanup/failure handler
                    "ResultPath": "$.result",  # Store error result in the `result` field
                }
            ],
            "ResultPath": "$.result",  # Store the Lambda output in `result` field of state data
        },
        # Cleanup task in case of failure (e.g., delete from DynamoDB)
        "Fallback - Delete failed order": {
            "Type": "Task",  # A task to perform DynamoDB deletion
            "Resource": "arn:aws:states:::dynamodb:deleteItem",  # Managed integration with DynamoDB
            # Parameters for DynamoDB DeleteItem API
            "Parameters": {
                "TableName": "CustomerOrdersTable",  # DynamoDB table to delete from
                "Key": {
                    "customerId": {
                        "S.$": "$.customerId"  # Take the value at path $.customerId from the input JSON, and use it as the value of a DynamoDB String-typed attribute.
                    },
                    "orderId": {
                        "S.$": "$.orderId"  # Use state input to provide orderId
                    },
                },
            },
            "Next": "Fail",  # After deleting, go to the Fail state
        },
        # Indicates successful completion
        "Success": {
            "Type": "Succeed"  # Terminates the execution successfully
        },
        # Indicates failure completion
        "Fail": {
            "Type": "Fail"  # Terminates execution with a failure
        },
    },
}

# Create the Step Function state machine
state_machine_name = 'ProcessOrders'
role_arn = 'arn:aws:iam::your-account-id:role/your-iam-role'  # Replace with your IAM role ARN

try:
    response = sfn_client.create_state_machine(
        name=state_machine_name,
        definition=json.dumps(state_machine_definition),
        roleArn=role_arn
    )
    print(f"Created Step Function with ARN: {response['stateMachineArn']}")
except sfn_client.exceptions.StateMachineAlreadyExists:
    print(f"Step Function {state_machine_name} already exists.")

# Replace 'your-account-id' and 'your-iam-role' with appropriate values
